version: '2'
services:
    testbot-mongodb:
        container_name: testbot-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/testBot/mongodb/:/data/db/
